
####################################################################################
# Generated by PlanAhead 14.7 built on 'Fri Sep 27 19:29:51 MDT 2013' by 'xbuild'
####################################################################################


####################################################################################
# Constraints from file : 'Nexys4UserDemo.ucf'
####################################################################################

#Nexys4 User Demo User Constraint File
# System Clock, 100MHz
set_property PACKAGE_PIN E3 [get_ports clk_i]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'clk_i' has been applied to the port object 'clk_i'.
set_property IOSTANDARD LVCMOS33 [get_ports clk_i]
# Active-Low Reset, CPU_RESET button
set_property PACKAGE_PIN C12 [get_ports rstn_i]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'rstn_i' has been applied to the port object 'rstn_i'.
set_property IOSTANDARD LVCMOS33 [get_ports rstn_i]

# Pushbuttons
set_property PACKAGE_PIN T16 [get_ports btnl_i]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'btnl_i' has been applied to the port object 'btnl_i'.
set_property IOSTANDARD LVCMOS33 [get_ports btnl_i]
set_property PACKAGE_PIN E16 [get_ports btnc_i]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'btnc_i' has been applied to the port object 'btnc_i'.
set_property IOSTANDARD LVCMOS33 [get_ports btnc_i]
set_property PACKAGE_PIN R10 [get_ports btnr_i]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'btnr_i' has been applied to the port object 'btnr_i'.
set_property IOSTANDARD LVCMOS33 [get_ports btnr_i]
set_property PACKAGE_PIN V10 [get_ports btnd_i]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'btnd_i' has been applied to the port object 'btnd_i'.
set_property IOSTANDARD LVCMOS33 [get_ports btnd_i]
set_property PACKAGE_PIN F15 [get_ports btnu_i]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'btnu_i' has been applied to the port object 'btnu_i'.
set_property IOSTANDARD LVCMOS33 [get_ports btnu_i]

set_property PACKAGE_PIN U9 [get_ports {sw_i[0]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'sw_i[0]' has been applied to the port object 'sw_i[0]'.
set_property IOSTANDARD LVCMOS33 [get_ports {sw_i[0]}]
set_property PACKAGE_PIN U8 [get_ports {sw_i[1]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'sw_i[1]' has been applied to the port object 'sw_i[1]'.
set_property IOSTANDARD LVCMOS33 [get_ports {sw_i[1]}]
set_property PACKAGE_PIN R7 [get_ports {sw_i[2]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'sw_i[2]' has been applied to the port object 'sw_i[2]'.
set_property IOSTANDARD LVCMOS33 [get_ports {sw_i[2]}]
set_property PACKAGE_PIN R6 [get_ports {sw_i[3]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'sw_i[3]' has been applied to the port object 'sw_i[3]'.
set_property IOSTANDARD LVCMOS33 [get_ports {sw_i[3]}]
set_property PACKAGE_PIN R5 [get_ports {sw_i[4]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'sw_i[4]' has been applied to the port object 'sw_i[4]'.
set_property IOSTANDARD LVCMOS33 [get_ports {sw_i[4]}]
set_property PACKAGE_PIN V7 [get_ports {sw_i[5]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'sw_i[5]' has been applied to the port object 'sw_i[5]'.
set_property IOSTANDARD LVCMOS33 [get_ports {sw_i[5]}]
set_property PACKAGE_PIN V6 [get_ports {sw_i[6]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'sw_i[6]' has been applied to the port object 'sw_i[6]'.
set_property IOSTANDARD LVCMOS33 [get_ports {sw_i[6]}]
set_property PACKAGE_PIN V5 [get_ports {sw_i[7]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'sw_i[7]' has been applied to the port object 'sw_i[7]'.
set_property IOSTANDARD LVCMOS33 [get_ports {sw_i[7]}]
set_property PACKAGE_PIN U4 [get_ports {sw_i[8]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'sw_i[8]' has been applied to the port object 'sw_i[8]'.
set_property IOSTANDARD LVCMOS33 [get_ports {sw_i[8]}]
set_property PACKAGE_PIN V2 [get_ports {sw_i[9]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'sw_i[9]' has been applied to the port object 'sw_i[9]'.
set_property IOSTANDARD LVCMOS33 [get_ports {sw_i[9]}]
set_property PACKAGE_PIN U2 [get_ports {sw_i[10]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'sw_i[10]' has been applied to the port object 'sw_i[10]'.
set_property IOSTANDARD LVCMOS33 [get_ports {sw_i[10]}]
set_property PACKAGE_PIN T3 [get_ports {sw_i[11]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'sw_i[11]' has been applied to the port object 'sw_i[11]'.
set_property IOSTANDARD LVCMOS33 [get_ports {sw_i[11]}]
set_property PACKAGE_PIN T1 [get_ports {sw_i[12]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'sw_i[12]' has been applied to the port object 'sw_i[12]'.
set_property IOSTANDARD LVCMOS33 [get_ports {sw_i[12]}]
set_property PACKAGE_PIN R3 [get_ports {sw_i[13]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'sw_i[13]' has been applied to the port object 'sw_i[13]'.
set_property IOSTANDARD LVCMOS33 [get_ports {sw_i[13]}]
set_property PACKAGE_PIN P3 [get_ports {sw_i[14]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'sw_i[14]' has been applied to the port object 'sw_i[14]'.
set_property IOSTANDARD LVCMOS33 [get_ports {sw_i[14]}]
set_property PACKAGE_PIN P4 [get_ports {sw_i[15]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'sw_i[15]' has been applied to the port object 'sw_i[15]'.
set_property IOSTANDARD LVCMOS33 [get_ports {sw_i[15]}]

# ADT7420 Temperature Sensor TWI Signals
#NET "tmp_ct"   LOC = "C14" |IOSTANDARD=LVCMOS33 | PULLUP;
#NET "tmp_int"  LOC = "D14" |IOSTANDARD=LVCMOS33 | PULLUP;
set_property PACKAGE_PIN F16 [get_ports tmp_scl]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'tmp_scl' has been applied to the port object 'tmp_scl'.
set_property IOSTANDARD LVCMOS33 [get_ports tmp_scl]
set_property PACKAGE_PIN G16 [get_ports tmp_sda]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'tmp_sda' has been applied to the port object 'tmp_sda'.
set_property IOSTANDARD LVCMOS33 [get_ports tmp_sda]

# ADXL362 Accelerometer SPI Signals
set_property PACKAGE_PIN C15 [get_ports ss]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'ss' has been applied to the port object 'ss'.
set_property IOSTANDARD LVCMOS33 [get_ports ss]
set_property PACKAGE_PIN D13 [get_ports miso]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'miso' has been applied to the port object 'miso'.
set_property IOSTANDARD LVCMOS33 [get_ports miso]
set_property PACKAGE_PIN B14 [get_ports mosi]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'mosi' has been applied to the port object 'mosi'.
set_property IOSTANDARD LVCMOS33 [get_ports mosi]
set_property PACKAGE_PIN D15 [get_ports sclk]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'sclk' has been applied to the port object 'sclk'.
set_property IOSTANDARD LVCMOS33 [get_ports sclk]

# 8-Digit Seven-Segment Display Segments
set_property PACKAGE_PIN L3 [get_ports {disp_seg_o[0]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'disp_seg_o[0]' has been applied to the port object 'disp_seg_o[0]'.
set_property IOSTANDARD LVCMOS33 [get_ports {disp_seg_o[0]}]
set_property PACKAGE_PIN N1 [get_ports {disp_seg_o[1]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'disp_seg_o[1]' has been applied to the port object 'disp_seg_o[1]'.
set_property IOSTANDARD LVCMOS33 [get_ports {disp_seg_o[1]}]
set_property PACKAGE_PIN L5 [get_ports {disp_seg_o[2]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'disp_seg_o[2]' has been applied to the port object 'disp_seg_o[2]'.
set_property IOSTANDARD LVCMOS33 [get_ports {disp_seg_o[2]}]
set_property PACKAGE_PIN L4 [get_ports {disp_seg_o[3]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'disp_seg_o[3]' has been applied to the port object 'disp_seg_o[3]'.
set_property IOSTANDARD LVCMOS33 [get_ports {disp_seg_o[3]}]
set_property PACKAGE_PIN K3 [get_ports {disp_seg_o[4]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'disp_seg_o[4]' has been applied to the port object 'disp_seg_o[4]'.
set_property IOSTANDARD LVCMOS33 [get_ports {disp_seg_o[4]}]
set_property PACKAGE_PIN M2 [get_ports {disp_seg_o[5]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'disp_seg_o[5]' has been applied to the port object 'disp_seg_o[5]'.
set_property IOSTANDARD LVCMOS33 [get_ports {disp_seg_o[5]}]
set_property PACKAGE_PIN L6 [get_ports {disp_seg_o[6]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'disp_seg_o[6]' has been applied to the port object 'disp_seg_o[6]'.
set_property IOSTANDARD LVCMOS33 [get_ports {disp_seg_o[6]}]
#DP
set_property PACKAGE_PIN M4 [get_ports {disp_seg_o[7]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'disp_seg_o[7]' has been applied to the port object 'disp_seg_o[7]'.
set_property IOSTANDARD LVCMOS33 [get_ports {disp_seg_o[7]}]
# 8-Digit Seven-Segment Display Anodes, Active-Low
set_property PACKAGE_PIN N6 [get_ports {disp_an_o[0]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'disp_an_o[0]' has been applied to the port object 'disp_an_o[0]'.
set_property IOSTANDARD LVCMOS33 [get_ports {disp_an_o[0]}]
set_property PACKAGE_PIN M6 [get_ports {disp_an_o[1]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'disp_an_o[1]' has been applied to the port object 'disp_an_o[1]'.
set_property IOSTANDARD LVCMOS33 [get_ports {disp_an_o[1]}]
set_property PACKAGE_PIN M3 [get_ports {disp_an_o[2]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'disp_an_o[2]' has been applied to the port object 'disp_an_o[2]'.
set_property IOSTANDARD LVCMOS33 [get_ports {disp_an_o[2]}]
set_property PACKAGE_PIN N5 [get_ports {disp_an_o[3]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'disp_an_o[3]' has been applied to the port object 'disp_an_o[3]'.
set_property IOSTANDARD LVCMOS33 [get_ports {disp_an_o[3]}]
set_property PACKAGE_PIN N2 [get_ports {disp_an_o[4]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'disp_an_o[4]' has been applied to the port object 'disp_an_o[4]'.
set_property IOSTANDARD LVCMOS33 [get_ports {disp_an_o[4]}]
set_property PACKAGE_PIN N4 [get_ports {disp_an_o[5]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'disp_an_o[5]' has been applied to the port object 'disp_an_o[5]'.
set_property IOSTANDARD LVCMOS33 [get_ports {disp_an_o[5]}]
set_property PACKAGE_PIN L1 [get_ports {disp_an_o[6]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'disp_an_o[6]' has been applied to the port object 'disp_an_o[6]'.
set_property IOSTANDARD LVCMOS33 [get_ports {disp_an_o[6]}]
set_property PACKAGE_PIN M1 [get_ports {disp_an_o[7]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'disp_an_o[7]' has been applied to the port object 'disp_an_o[7]'.
set_property IOSTANDARD LVCMOS33 [get_ports {disp_an_o[7]}]

# LD16 RGB LED Signals
set_property PACKAGE_PIN K5 [get_ports rgb1_red_o]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'rgb1_red_o' has been applied to the port object 'rgb1_red_o'.
set_property IOSTANDARD LVCMOS33 [get_ports rgb1_red_o]
set_property PACKAGE_PIN F13 [get_ports rgb1_green_o]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'rgb1_green_o' has been applied to the port object 'rgb1_green_o'.
set_property IOSTANDARD LVCMOS33 [get_ports rgb1_green_o]
set_property PACKAGE_PIN F6 [get_ports rgb1_blue_o]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'rgb1_blue_o' has been applied to the port object 'rgb1_blue_o'.
set_property IOSTANDARD LVCMOS33 [get_ports rgb1_blue_o]
# LD17 RGB LED Signals
set_property PACKAGE_PIN K6 [get_ports rgb2_red_o]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'rgb2_red_o' has been applied to the port object 'rgb2_red_o'.
set_property IOSTANDARD LVCMOS33 [get_ports rgb2_red_o]
set_property PACKAGE_PIN H6 [get_ports rgb2_green_o]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'rgb2_green_o' has been applied to the port object 'rgb2_green_o'.
set_property IOSTANDARD LVCMOS33 [get_ports rgb2_green_o]
set_property PACKAGE_PIN L16 [get_ports rgb2_blue_o]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'rgb2_blue_o' has been applied to the port object 'rgb2_blue_o'.
set_property IOSTANDARD LVCMOS33 [get_ports rgb2_blue_o]
# LEDs
set_property PACKAGE_PIN T8 [get_ports {led_o[0]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'led_o[0]' has been applied to the port object 'led_o[0]'.
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[0]}]
set_property PACKAGE_PIN V9 [get_ports {led_o[1]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'led_o[1]' has been applied to the port object 'led_o[1]'.
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[1]}]
set_property PACKAGE_PIN R8 [get_ports {led_o[2]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'led_o[2]' has been applied to the port object 'led_o[2]'.
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[2]}]
set_property PACKAGE_PIN T6 [get_ports {led_o[3]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'led_o[3]' has been applied to the port object 'led_o[3]'.
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[3]}]
set_property PACKAGE_PIN T5 [get_ports {led_o[4]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'led_o[4]' has been applied to the port object 'led_o[4]'.
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[4]}]
set_property PACKAGE_PIN T4 [get_ports {led_o[5]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'led_o[5]' has been applied to the port object 'led_o[5]'.
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[5]}]
set_property PACKAGE_PIN U7 [get_ports {led_o[6]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'led_o[6]' has been applied to the port object 'led_o[6]'.
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[6]}]
set_property PACKAGE_PIN U6 [get_ports {led_o[7]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'led_o[7]' has been applied to the port object 'led_o[7]'.
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[7]}]
set_property PACKAGE_PIN V4 [get_ports {led_o[8]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'led_o[8]' has been applied to the port object 'led_o[8]'.
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[8]}]
set_property PACKAGE_PIN U3 [get_ports {led_o[9]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'led_o[9]' has been applied to the port object 'led_o[9]'.
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[9]}]
set_property PACKAGE_PIN V1 [get_ports {led_o[10]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'led_o[10]' has been applied to the port object 'led_o[10]'.
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[10]}]
set_property PACKAGE_PIN R1 [get_ports {led_o[11]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'led_o[11]' has been applied to the port object 'led_o[11]'.
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[11]}]
set_property PACKAGE_PIN P5 [get_ports {led_o[12]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'led_o[12]' has been applied to the port object 'led_o[12]'.
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[12]}]
set_property PACKAGE_PIN U1 [get_ports {led_o[13]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'led_o[13]' has been applied to the port object 'led_o[13]'.
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[13]}]
set_property PACKAGE_PIN R2 [get_ports {led_o[14]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'led_o[14]' has been applied to the port object 'led_o[14]'.
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[14]}]
set_property PACKAGE_PIN P2 [get_ports {led_o[15]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'led_o[15]' has been applied to the port object 'led_o[15]'.
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[15]}]

# VGA Signals
set_property PACKAGE_PIN A3 [get_ports {vga_red_o[0]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vga_red_o[0]' has been applied to the port object 'vga_red_o[0]'.
set_property IOSTANDARD LVCMOS33 [get_ports {vga_red_o[0]}]
# The conversion of 'SLEW' constraint on 'net' object 'vga_red_o[0]' has been applied to the port object 'vga_red_o[0]'.
set_property SLEW FAST [get_ports {vga_red_o[0]}]
set_property PACKAGE_PIN B4 [get_ports {vga_red_o[1]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vga_red_o[1]' has been applied to the port object 'vga_red_o[1]'.
set_property IOSTANDARD LVCMOS33 [get_ports {vga_red_o[1]}]
# The conversion of 'SLEW' constraint on 'net' object 'vga_red_o[1]' has been applied to the port object 'vga_red_o[1]'.
set_property SLEW FAST [get_ports {vga_red_o[1]}]
set_property PACKAGE_PIN C5 [get_ports {vga_red_o[2]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vga_red_o[2]' has been applied to the port object 'vga_red_o[2]'.
set_property IOSTANDARD LVCMOS33 [get_ports {vga_red_o[2]}]
# The conversion of 'SLEW' constraint on 'net' object 'vga_red_o[2]' has been applied to the port object 'vga_red_o[2]'.
set_property SLEW FAST [get_ports {vga_red_o[2]}]
set_property PACKAGE_PIN A4 [get_ports {vga_red_o[3]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vga_red_o[3]' has been applied to the port object 'vga_red_o[3]'.
set_property IOSTANDARD LVCMOS33 [get_ports {vga_red_o[3]}]
# The conversion of 'SLEW' constraint on 'net' object 'vga_red_o[3]' has been applied to the port object 'vga_red_o[3]'.
set_property SLEW FAST [get_ports {vga_red_o[3]}]
set_property PACKAGE_PIN B7 [get_ports {vga_blue_o[0]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vga_blue_o[0]' has been applied to the port object 'vga_blue_o[0]'.
set_property IOSTANDARD LVCMOS33 [get_ports {vga_blue_o[0]}]
# The conversion of 'SLEW' constraint on 'net' object 'vga_blue_o[0]' has been applied to the port object 'vga_blue_o[0]'.
set_property SLEW FAST [get_ports {vga_blue_o[0]}]
set_property PACKAGE_PIN C7 [get_ports {vga_blue_o[1]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vga_blue_o[1]' has been applied to the port object 'vga_blue_o[1]'.
set_property IOSTANDARD LVCMOS33 [get_ports {vga_blue_o[1]}]
# The conversion of 'SLEW' constraint on 'net' object 'vga_blue_o[1]' has been applied to the port object 'vga_blue_o[1]'.
set_property SLEW FAST [get_ports {vga_blue_o[1]}]
set_property PACKAGE_PIN D7 [get_ports {vga_blue_o[2]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vga_blue_o[2]' has been applied to the port object 'vga_blue_o[2]'.
set_property IOSTANDARD LVCMOS33 [get_ports {vga_blue_o[2]}]
# The conversion of 'SLEW' constraint on 'net' object 'vga_blue_o[2]' has been applied to the port object 'vga_blue_o[2]'.
set_property SLEW FAST [get_ports {vga_blue_o[2]}]
set_property PACKAGE_PIN D8 [get_ports {vga_blue_o[3]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vga_blue_o[3]' has been applied to the port object 'vga_blue_o[3]'.
set_property IOSTANDARD LVCMOS33 [get_ports {vga_blue_o[3]}]
# The conversion of 'SLEW' constraint on 'net' object 'vga_blue_o[3]' has been applied to the port object 'vga_blue_o[3]'.
set_property SLEW FAST [get_ports {vga_blue_o[3]}]
set_property PACKAGE_PIN C6 [get_ports {vga_green_o[0]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vga_green_o[0]' has been applied to the port object 'vga_green_o[0]'.
set_property IOSTANDARD LVCMOS33 [get_ports {vga_green_o[0]}]
# The conversion of 'SLEW' constraint on 'net' object 'vga_green_o[0]' has been applied to the port object 'vga_green_o[0]'.
set_property SLEW FAST [get_ports {vga_green_o[0]}]
set_property PACKAGE_PIN A5 [get_ports {vga_green_o[1]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vga_green_o[1]' has been applied to the port object 'vga_green_o[1]'.
set_property IOSTANDARD LVCMOS33 [get_ports {vga_green_o[1]}]
# The conversion of 'SLEW' constraint on 'net' object 'vga_green_o[1]' has been applied to the port object 'vga_green_o[1]'.
set_property SLEW FAST [get_ports {vga_green_o[1]}]
set_property PACKAGE_PIN B6 [get_ports {vga_green_o[2]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vga_green_o[2]' has been applied to the port object 'vga_green_o[2]'.
set_property IOSTANDARD LVCMOS33 [get_ports {vga_green_o[2]}]
# The conversion of 'SLEW' constraint on 'net' object 'vga_green_o[2]' has been applied to the port object 'vga_green_o[2]'.
set_property SLEW FAST [get_ports {vga_green_o[2]}]
set_property PACKAGE_PIN A6 [get_ports {vga_green_o[3]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vga_green_o[3]' has been applied to the port object 'vga_green_o[3]'.
set_property IOSTANDARD LVCMOS33 [get_ports {vga_green_o[3]}]
# The conversion of 'SLEW' constraint on 'net' object 'vga_green_o[3]' has been applied to the port object 'vga_green_o[3]'.
set_property SLEW FAST [get_ports {vga_green_o[3]}]
set_property PACKAGE_PIN B11 [get_ports vga_hs_o]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vga_hs_o' has been applied to the port object 'vga_hs_o'.
set_property IOSTANDARD LVCMOS33 [get_ports vga_hs_o]
# The conversion of 'SLEW' constraint on 'net' object 'vga_hs_o' has been applied to the port object 'vga_hs_o'.
set_property SLEW FAST [get_ports vga_hs_o]
set_property PACKAGE_PIN B12 [get_ports vga_vs_o]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vga_vs_o' has been applied to the port object 'vga_vs_o'.
set_property IOSTANDARD LVCMOS33 [get_ports vga_vs_o]
# The conversion of 'SLEW' constraint on 'net' object 'vga_vs_o' has been applied to the port object 'vga_vs_o'.
set_property SLEW FAST [get_ports vga_vs_o]

# ADMP421 Omnidirectional Microphone Signals
set_property PACKAGE_PIN J5 [get_ports pdm_clk_o]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'pdm_clk_o' has been applied to the port object 'pdm_clk_o'.
set_property IOSTANDARD LVCMOS33 [get_ports pdm_clk_o]
set_property PACKAGE_PIN H5 [get_ports pdm_data_i]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'pdm_data_i' has been applied to the port object 'pdm_data_i'.
set_property IOSTANDARD LVCMOS33 [get_ports pdm_data_i]
set_property PACKAGE_PIN F5 [get_ports pdm_lrsel_o]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'pdm_lrsel_o' has been applied to the port object 'pdm_lrsel_o'.
set_property IOSTANDARD LVCMOS33 [get_ports pdm_lrsel_o]

# Audio Out Signals
set_property PACKAGE_PIN A11 [get_ports pwm_audio_o]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'pwm_audio_o' has been applied to the port object 'pwm_audio_o'.
set_property IOSTANDARD LVCMOS33 [get_ports pwm_audio_o]
set_property PACKAGE_PIN D12 [get_ports pwm_sdaudio_o]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'pwm_sdaudio_o' has been applied to the port object 'pwm_sdaudio_o'.
set_property IOSTANDARD LVCMOS33 [get_ports pwm_sdaudio_o]

# PSRAM Memory Signals
set_property PACKAGE_PIN J18 [get_ports {Mem_A[0]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_A[0]' has been applied to the port object 'Mem_A[0]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_A[0]}]
set_property PACKAGE_PIN H17 [get_ports {Mem_A[1]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_A[1]' has been applied to the port object 'Mem_A[1]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_A[1]}]
set_property PACKAGE_PIN H15 [get_ports {Mem_A[2]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_A[2]' has been applied to the port object 'Mem_A[2]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_A[2]}]
set_property PACKAGE_PIN J17 [get_ports {Mem_A[3]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_A[3]' has been applied to the port object 'Mem_A[3]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_A[3]}]
set_property PACKAGE_PIN H16 [get_ports {Mem_A[4]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_A[4]' has been applied to the port object 'Mem_A[4]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_A[4]}]
set_property PACKAGE_PIN K15 [get_ports {Mem_A[5]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_A[5]' has been applied to the port object 'Mem_A[5]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_A[5]}]
set_property PACKAGE_PIN K13 [get_ports {Mem_A[6]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_A[6]' has been applied to the port object 'Mem_A[6]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_A[6]}]
set_property PACKAGE_PIN N15 [get_ports {Mem_A[7]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_A[7]' has been applied to the port object 'Mem_A[7]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_A[7]}]
set_property PACKAGE_PIN V16 [get_ports {Mem_A[8]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_A[8]' has been applied to the port object 'Mem_A[8]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_A[8]}]
set_property PACKAGE_PIN U14 [get_ports {Mem_A[9]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_A[9]' has been applied to the port object 'Mem_A[9]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_A[9]}]
set_property PACKAGE_PIN V14 [get_ports {Mem_A[10]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_A[10]' has been applied to the port object 'Mem_A[10]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_A[10]}]
set_property PACKAGE_PIN V12 [get_ports {Mem_A[11]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_A[11]' has been applied to the port object 'Mem_A[11]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_A[11]}]
set_property PACKAGE_PIN P14 [get_ports {Mem_A[12]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_A[12]' has been applied to the port object 'Mem_A[12]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_A[12]}]
set_property PACKAGE_PIN U16 [get_ports {Mem_A[13]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_A[13]' has been applied to the port object 'Mem_A[13]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_A[13]}]
set_property PACKAGE_PIN R15 [get_ports {Mem_A[14]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_A[14]' has been applied to the port object 'Mem_A[14]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_A[14]}]
set_property PACKAGE_PIN N14 [get_ports {Mem_A[15]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_A[15]' has been applied to the port object 'Mem_A[15]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_A[15]}]
set_property PACKAGE_PIN N16 [get_ports {Mem_A[16]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_A[16]' has been applied to the port object 'Mem_A[16]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_A[16]}]
set_property PACKAGE_PIN M13 [get_ports {Mem_A[17]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_A[17]' has been applied to the port object 'Mem_A[17]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_A[17]}]
set_property PACKAGE_PIN V17 [get_ports {Mem_A[18]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_A[18]' has been applied to the port object 'Mem_A[18]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_A[18]}]
set_property PACKAGE_PIN U17 [get_ports {Mem_A[19]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_A[19]' has been applied to the port object 'Mem_A[19]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_A[19]}]
set_property PACKAGE_PIN T10 [get_ports {Mem_A[20]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_A[20]' has been applied to the port object 'Mem_A[20]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_A[20]}]
set_property PACKAGE_PIN M16 [get_ports {Mem_A[21]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_A[21]' has been applied to the port object 'Mem_A[21]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_A[21]}]
set_property PACKAGE_PIN U13 [get_ports {Mem_A[22]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_A[22]' has been applied to the port object 'Mem_A[22]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_A[22]}]
set_property PACKAGE_PIN R11 [get_ports Mem_WEN]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_WEN' has been applied to the port object 'Mem_WEN'.
set_property IOSTANDARD LVCMOS33 [get_ports Mem_WEN]
set_property PACKAGE_PIN H14 [get_ports Mem_OEN]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_OEN' has been applied to the port object 'Mem_OEN'.
set_property IOSTANDARD LVCMOS33 [get_ports Mem_OEN]
set_property PACKAGE_PIN L18 [get_ports Mem_CEN]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_CEN' has been applied to the port object 'Mem_CEN'.
set_property IOSTANDARD LVCMOS33 [get_ports Mem_CEN]
set_property PACKAGE_PIN J13 [get_ports Mem_UB]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_UB' has been applied to the port object 'Mem_UB'.
set_property IOSTANDARD LVCMOS33 [get_ports Mem_UB]
set_property PACKAGE_PIN J15 [get_ports Mem_LB]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_LB' has been applied to the port object 'Mem_LB'.
set_property IOSTANDARD LVCMOS33 [get_ports Mem_LB]
set_property PACKAGE_PIN T15 [get_ports Mem_CLK]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_CLK' has been applied to the port object 'Mem_CLK'.
set_property IOSTANDARD LVCMOS33 [get_ports Mem_CLK]
set_property PACKAGE_PIN T13 [get_ports Mem_ADV]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_ADV' has been applied to the port object 'Mem_ADV'.
set_property IOSTANDARD LVCMOS33 [get_ports Mem_ADV]
set_property PACKAGE_PIN J14 [get_ports Mem_CRE]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_CRE' has been applied to the port object 'Mem_CRE'.
set_property IOSTANDARD LVCMOS33 [get_ports Mem_CRE]
set_property PACKAGE_PIN R12 [get_ports {Mem_DQ[0]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_DQ[0]' has been applied to the port object 'Mem_DQ[0]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_DQ[0]}]
set_property PACKAGE_PIN T11 [get_ports {Mem_DQ[1]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_DQ[1]' has been applied to the port object 'Mem_DQ[1]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_DQ[1]}]
set_property PACKAGE_PIN U12 [get_ports {Mem_DQ[2]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_DQ[2]' has been applied to the port object 'Mem_DQ[2]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_DQ[2]}]
set_property PACKAGE_PIN R13 [get_ports {Mem_DQ[3]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_DQ[3]' has been applied to the port object 'Mem_DQ[3]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_DQ[3]}]
set_property PACKAGE_PIN U18 [get_ports {Mem_DQ[4]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_DQ[4]' has been applied to the port object 'Mem_DQ[4]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_DQ[4]}]
set_property PACKAGE_PIN R17 [get_ports {Mem_DQ[5]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_DQ[5]' has been applied to the port object 'Mem_DQ[5]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_DQ[5]}]
set_property PACKAGE_PIN T18 [get_ports {Mem_DQ[6]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_DQ[6]' has been applied to the port object 'Mem_DQ[6]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_DQ[6]}]
set_property PACKAGE_PIN R18 [get_ports {Mem_DQ[7]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_DQ[7]' has been applied to the port object 'Mem_DQ[7]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_DQ[7]}]
set_property PACKAGE_PIN F18 [get_ports {Mem_DQ[8]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_DQ[8]' has been applied to the port object 'Mem_DQ[8]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_DQ[8]}]
set_property PACKAGE_PIN G18 [get_ports {Mem_DQ[9]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_DQ[9]' has been applied to the port object 'Mem_DQ[9]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_DQ[9]}]
set_property PACKAGE_PIN G17 [get_ports {Mem_DQ[10]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_DQ[10]' has been applied to the port object 'Mem_DQ[10]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_DQ[10]}]
set_property PACKAGE_PIN M18 [get_ports {Mem_DQ[11]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_DQ[11]' has been applied to the port object 'Mem_DQ[11]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_DQ[11]}]
set_property PACKAGE_PIN M17 [get_ports {Mem_DQ[12]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_DQ[12]' has been applied to the port object 'Mem_DQ[12]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_DQ[12]}]
set_property PACKAGE_PIN P18 [get_ports {Mem_DQ[13]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_DQ[13]' has been applied to the port object 'Mem_DQ[13]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_DQ[13]}]
set_property PACKAGE_PIN N17 [get_ports {Mem_DQ[14]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_DQ[14]' has been applied to the port object 'Mem_DQ[14]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_DQ[14]}]
set_property PACKAGE_PIN P17 [get_ports {Mem_DQ[15]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_DQ[15]' has been applied to the port object 'Mem_DQ[15]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_DQ[15]}]

# PS2 Signals
set_property PACKAGE_PIN F4 [get_ports ps2_clk]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'ps2_clk' has been applied to the port object 'ps2_clk'.
set_property IOSTANDARD LVCMOS33 [get_ports ps2_clk]
# The conversion of 'PULL' constraint on 'net' object 'ps2_clk' has been applied to the port object 'ps2_clk'.
set_property PULLUP true [get_ports ps2_clk]
set_property PACKAGE_PIN B2 [get_ports ps2_data]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'ps2_data' has been applied to the port object 'ps2_data'.
set_property IOSTANDARD LVCMOS33 [get_ports ps2_data]
# The conversion of 'PULL' constraint on 'net' object 'ps2_data' has been applied to the port object 'ps2_data'.
set_property PULLUP true [get_ports ps2_data]

# Incoming System Clock PERIOD Constraint

# All timing constraint translations are rough conversions, intended to act as a template for further manual refinement. The translations should not be expected to produce semantically identical results to the original ucf. Each xdc timing constraint must be manually inspected and verified to ensure it captures the desired intent

create_clock -name clk_i -period 10.000 [get_ports clk_i]

# Ignore Clock Domain Crossing signals
# These signals are coming from the 100MHz clock domain
# ant are not time-critical: RGB LED, Temperature, Accelerometer
# and Mouse Controller data, going to the 108Mhz clock domain, the VGA display controller

# Define a new TNM for a FROM - TO constraint

get_false_path -from [all_fanout -endpoints_only -only_cells -flat -from [get_nets clk_i]] -to [all_fanout -endpoints_only -flat -from [get_nets Inst_VGA/pxl_clk]]
